server:
  port: 9098

#开发配置
spring:
  profiles: dev
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lcn?serverTimezone=GMT%2B8
    username: root
    password: ls123
  application:
    name: order
---
#默认使用配置
spring:
  profiles:
    active: dev
mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.ls.pojo
  mapperLocations: classpath:mappers/*.xml

logging:
  level:
    com.ls.mapper: debug
eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/