server:
  port: 9090

#开发配置
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth-oauth2?serverTimezone=GMT%2B8
    username: root
    password: ls123
  redis:
    host: 192.168.221.138
    port: 7000
mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.ls.auth.pojo
  mapperLocations: classpath:mappers/*.xml
mybatis-plus:
    map-underscore-to-camel-case: true
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.ls.auth.pojo
logging:
  level:
    com.sz566.auth.mapper: debug
