server:
  port: 9099
spring:
  application:
    name: web-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
feign:
  hystrix:
    enabled: true